package types

import "fmt"

type Variable struct {
	Name     VariableName `yaml:"name"`
	Excluded bool         `yaml:"excluded,omitempty"`
}

type VariableName int

const (
	UNKNOWN_VAR VariableName = iota
	ARGS_COMBINED_SIZE
	AUTH_TYPE
	DURATION
	FILES_COMBINED_SIZE
	FILES_NAMES
	FILES_SIZES
	FILES_TMP_CONTENT
	FILES_TMPNAMES
	FULL_REQUEST
	FULL_REQUEST_LENGTH
	HIGHEST_SEVERITY
	INBOUND_DATA_ERROR
	MATCHED_VAR
	MATCHED_VAR_NAME
	MODSEC_BUILD
	MSC_PCRE_LIMITS_EXCEEDED
	MULTIPART_CRLF_LF_LINES
	MULTIPART_FILENAME
	MULTIPART_NAME
	MULTIPART_STRICT_ERROR
	MULTIPART_UNMATCHED_BOUNDARY
	OUTBOUND_DATA_ERROR
	PATH_INFO
	PERF_ALL
	PERF_COMBINED
	PERF_GC
	PERF_LOGGING
	PERF_PHASE1
	PERF_PHASE2
	PERF_PHASE3
	PERF_PHASE4
	PERF_PHASE5
	PERF_SREAD
	PERF_SWRITE
	QUERY_STRING
	REMOTE_ADDR
	REMOTE_HOST
	REMOTE_PORT
	REMOTE_USER
	REQBODY_ERROR
	REQBODY_ERROR_MSG
	REQBODY_PROCESSOR
	REQUEST_BASENAME
	REQUEST_BODY
	REQUEST_BODY_LENGTH
	REQUEST_FILENAME
	REQUEST_LINE
	REQUEST_METHOD
	REQUEST_PROTOCOL
	REQUEST_URI
	REQUEST_URI_RAW
	RESPONSE_BODY
	RESPONSE_CONTENT_LENGTH
	RESPONSE_CONTENT_TYPE
	RESPONSE_PROTOCOL
	RESPONSE_STATUS
	SCRIPT_BASENAME
	SCRIPT_FILENAME
	SCRIPT_GID
	SCRIPT_GROUPNAME
	SCRIPT_MODE
	SCRIPT_UID
	SCRIPT_USERNAME
	SDBM_DELETE_ERROR
	SERVER_ADDR
	SERVER_NAME
	SERVER_PORT
	SESSIONID
	STATUS_LINE
	STREAM_INPUT_BODY
	STREAM_OUTPUT_BODY
	TIME
	TIME_DAY
	TIME_EPOCH
	TIME_HOUR
	TIME_MIN
	TIME_MON
	TIME_SEC
	TIME_WDAY
	TIME_YEAR
	UNIQUE_ID
	URLENCODED_ERROR
	USERAGENT_IP
	USERID
	WEBAPPID
	WEBSERVER_ERROR_LOG
	MSC_PCRE_ERROR
	MULTIPART_BOUNDARY_QUOTED
	MULTIPART_BOUNDARY_WHITESPACE
	MULTIPART_DATA_AFTER
	MULTIPART_DATA_BEFORE
	MULTIPART_FILE_LIMIT_EXCEEDED
	MULTIPART_HEADER_FOLDING
	MULTIPART_INVALID_HEADER_FOLDING
	MULTIPART_INVALID_PART
	MULTIPART_INVALID_QUOTING
	MULTIPART_LF_LINE
	MULTIPART_MISSING_SEMICOLON
	MULTIPART_SEMICOLON_MISSING
	REQBODY_PROCESSOR_ERROR
	REQBODY_PROCESSOR_ERROR_MSG
	STATUS
)

func (v VariableName) String() string {
	switch v {
	case ARGS_COMBINED_SIZE:
		return "ARGS_COMBINED_SIZE"
	case AUTH_TYPE:
		return "AUTH_TYPE"
	case DURATION:
		return "DURATION"
	case FILES_COMBINED_SIZE:
		return "FILES_COMBINED_SIZE"
	case FILES_NAMES:
		return "FILES_NAMES"
	case FILES_SIZES:
		return "FILES_SIZES"
	case FILES_TMP_CONTENT:
		return "FILES_TMP_CONTENT"
	case FILES_TMPNAMES:
		return "FILES_TMPNAMES"
	case FULL_REQUEST:
		return "FULL_REQUEST"
	case FULL_REQUEST_LENGTH:
		return "FULL_REQUEST_LENGTH"
	case HIGHEST_SEVERITY:
		return "HIGHEST_SEVERITY"
	case INBOUND_DATA_ERROR:
		return "INBOUND_DATA_ERROR"
	case MATCHED_VAR:
		return "MATCHED_VAR"
	case MATCHED_VAR_NAME:
		return "MATCHED_VAR_NAME"
	case MODSEC_BUILD:
		return "MODSEC_BUILD"
	case MSC_PCRE_LIMITS_EXCEEDED:
		return "MSC_PCRE_LIMITS_EXCEEDED"
	case MULTIPART_CRLF_LF_LINES:
		return "MULTIPART_CRLF_LF_LINES"
	case MULTIPART_FILENAME:
		return "MULTIPART_FILENAME"
	case MULTIPART_NAME:
		return "MULTIPART_NAME"
	case MULTIPART_STRICT_ERROR:
		return "MULTIPART_STRICT_ERROR"
	case MULTIPART_UNMATCHED_BOUNDARY:
		return "MULTIPART_UNMATCHED_BOUNDARY"
	case OUTBOUND_DATA_ERROR:
		return "OUTBOUND_DATA_ERROR"
	case PATH_INFO:
		return "PATH_INFO"
	case PERF_ALL:
		return "PERF_ALL"
	case PERF_COMBINED:
		return "PERF_COMBINED"
	case PERF_GC:
		return "PERF_GC"
	case PERF_LOGGING:
		return "PERF_LOGGING"
	case PERF_PHASE1:
		return "PERF_PHASE1"
	case PERF_PHASE2:
		return "PERF_PHASE2"
	case PERF_PHASE3:
		return "PERF_PHASE3"
	case PERF_PHASE4:
		return "PERF_PHASE4"
	case PERF_PHASE5:
		return "PERF_PHASE5"
	case PERF_SREAD:
		return "PERF_SREAD"
	case PERF_SWRITE:
		return "PERF_SWRITE"
	case QUERY_STRING:
		return "QUERY_STRING"
	case REMOTE_ADDR:
		return "REMOTE_ADDR"
	case REMOTE_HOST:
		return "REMOTE_HOST"
	case REMOTE_PORT:
		return "REMOTE_PORT"
	case REMOTE_USER:
		return "REMOTE_USER"
	case REQBODY_ERROR:
		return "REQBODY_ERROR"
	case REQBODY_ERROR_MSG:
		return "REQBODY_ERROR_MSG"
	case REQBODY_PROCESSOR:
		return "REQBODY_PROCESSOR"
	case REQUEST_BASENAME:
		return "REQUEST_BASENAME"
	case REQUEST_BODY:
		return "REQUEST_BODY"
	case REQUEST_BODY_LENGTH:
		return "REQUEST_BODY_LENGTH"
	case REQUEST_FILENAME:
		return "REQUEST_FILENAME"
	case REQUEST_LINE:
		return "REQUEST_LINE"
	case REQUEST_METHOD:
		return "REQUEST_METHOD"
	case REQUEST_PROTOCOL:
		return "REQUEST_PROTOCOL"
	case REQUEST_URI:
		return "REQUEST_URI"
	case REQUEST_URI_RAW:
		return "REQUEST_URI_RAW"
	case RESPONSE_BODY:
		return "RESPONSE_BODY"
	case RESPONSE_CONTENT_LENGTH:
		return "RESPONSE_CONTENT_LENGTH"
	case RESPONSE_CONTENT_TYPE:
		return "RESPONSE_CONTENT_TYPE"
	case RESPONSE_PROTOCOL:
		return "RESPONSE_PROTOCOL"
	case RESPONSE_STATUS:
		return "RESPONSE_STATUS"
	case SCRIPT_BASENAME:
		return "SCRIPT_BASENAME"
	case SCRIPT_FILENAME:
		return "SCRIPT_FILENAME"
	case SCRIPT_GID:
		return "SCRIPT_GID"
	case SCRIPT_GROUPNAME:
		return "SCRIPT_GROUPNAME"
	case SCRIPT_MODE:
		return "SCRIPT_MODE"
	case SCRIPT_UID:
		return "SCRIPT_UID"
	case SCRIPT_USERNAME:
		return "SCRIPT_USERNAME"
	case SDBM_DELETE_ERROR:
		return "SDBM_DELETE_ERROR"
	case SERVER_ADDR:
		return "SERVER_ADDR"
	case SERVER_NAME:
		return "SERVER_NAME"
	case SERVER_PORT:
		return "SERVER_PORT"
	case SESSIONID:
		return "SESSIONID"
	case STATUS_LINE:
		return "STATUS_LINE"
	case STREAM_INPUT_BODY:
		return "STREAM_INPUT_BODY"
	case STREAM_OUTPUT_BODY:
		return "STREAM_OUTPUT_BODY"
	case TIME:
		return "TIME"
	case TIME_DAY:
		return "TIME_DAY"
	case TIME_EPOCH:
		return "TIME_EPOCH"
	case TIME_HOUR:
		return "TIME_HOUR"
	case TIME_MIN:
		return "TIME_MIN"
	case TIME_MON:
		return "TIME_MON"
	case TIME_SEC:
		return "TIME_SEC"
	case TIME_WDAY:
		return "TIME_WDAY"
	case TIME_YEAR:
		return "TIME_YEAR"
	case UNIQUE_ID:
		return "UNIQUE_ID"
	case URLENCODED_ERROR:
		return "URLENCODED_ERROR"
	case USERAGENT_IP:
		return "USERAGENT_IP"
	case USERID:
		return "USERID"
	case WEBAPPID:
		return "WEBAPPID"
	case WEBSERVER_ERROR_LOG:
		return "WEBSERVER_ERROR_LOG"
	case MSC_PCRE_ERROR:
		return "MSC_PCRE_ERROR"
	case MULTIPART_BOUNDARY_QUOTED:
		return "MULTIPART_BOUNDARY_QUOTED"
	case MULTIPART_BOUNDARY_WHITESPACE:
		return "MULTIPART_BOUNDARY_WHITESPACE"
	case MULTIPART_DATA_AFTER:
		return "MULTIPART_DATA_AFTER"
	case MULTIPART_DATA_BEFORE:
		return "MULTIPART_DATA_BEFORE"
	case MULTIPART_FILE_LIMIT_EXCEEDED:
		return "MULTIPART_FILE_LIMIT_EXCEEDED"
	case MULTIPART_HEADER_FOLDING:
		return "MULTIPART_HEADER_FOLDING"
	case MULTIPART_INVALID_HEADER_FOLDING:
		return "MULTIPART_INVALID_HEADER_FOLDING"
	case MULTIPART_INVALID_PART:
		return "MULTIPART_INVALID_PART"
	case MULTIPART_INVALID_QUOTING:
		return "MULTIPART_INVALID_QUOTING"
	case MULTIPART_LF_LINE:
		return "MULTIPART_LF_LINE"
	case MULTIPART_MISSING_SEMICOLON:
		return "MULTIPART_MISSING_SEMICOLON"
	case MULTIPART_SEMICOLON_MISSING:
		return "MULTIPART_SEMICOLON_MISSING"
	case REQBODY_PROCESSOR_ERROR:
		return "REQBODY_PROCESSOR_ERROR"
	case REQBODY_PROCESSOR_ERROR_MSG:
		return "REQBODY_PROCESSOR_ERROR_MSG"
	case STATUS:
		return "STATUS"
	default:
		return "UNKNOWN_VAR"
	}
}

var (
	allVariables = map[string]VariableName{
		"ARGS_COMBINED_SIZE":               ARGS_COMBINED_SIZE,
		"AUTH_TYPE":                        AUTH_TYPE,
		"DURATION":                         DURATION,
		"FILES_COMBINED_SIZE":              FILES_COMBINED_SIZE,
		"FILES_NAMES":                      FILES_NAMES,
		"FILES_SIZES":                      FILES_SIZES,
		"FILES_TMP_CONTENT":                FILES_TMP_CONTENT,
		"FILES_TMPNAMES":                   FILES_TMPNAMES,
		"FULL_REQUEST":                     FULL_REQUEST,
		"FULL_REQUEST_LENGTH":              FULL_REQUEST_LENGTH,
		"HIGHEST_SEVERITY":                 HIGHEST_SEVERITY,
		"INBOUND_DATA_ERROR":               INBOUND_DATA_ERROR,
		"MATCHED_VAR":                      MATCHED_VAR,
		"MATCHED_VAR_NAME":                 MATCHED_VAR_NAME,
		"MODSEC_BUILD":                     MODSEC_BUILD,
		"MSC_PCRE_LIMITS_EXCEEDED":         MSC_PCRE_LIMITS_EXCEEDED,
		"MULTIPART_CRLF_LF_LINES":          MULTIPART_CRLF_LF_LINES,
		"MULTIPART_FILENAME":               MULTIPART_FILENAME,
		"MULTIPART_NAME":                   MULTIPART_NAME,
		"MULTIPART_STRICT_ERROR":           MULTIPART_STRICT_ERROR,
		"MULTIPART_UNMATCHED_BOUNDARY":     MULTIPART_UNMATCHED_BOUNDARY,
		"OUTBOUND_DATA_ERROR":              OUTBOUND_DATA_ERROR,
		"PATH_INFO":                        PATH_INFO,
		"PERF_ALL":                         PERF_ALL,
		"PERF_COMBINED":                    PERF_COMBINED,
		"PERF_GC":                          PERF_GC,
		"PERF_LOGGING":                     PERF_LOGGING,
		"PERF_PHASE1":                      PERF_PHASE1,
		"PERF_PHASE2":                      PERF_PHASE2,
		"PERF_PHASE3":                      PERF_PHASE3,
		"PERF_PHASE4":                      PERF_PHASE4,
		"PERF_PHASE5":                      PERF_PHASE5,
		"PERF_SREAD":                       PERF_SREAD,
		"PERF_SWRITE":                      PERF_SWRITE,
		"QUERY_STRING":                     QUERY_STRING,
		"REMOTE_ADDR":                      REMOTE_ADDR,
		"REMOTE_HOST":                      REMOTE_HOST,
		"REMOTE_PORT":                      REMOTE_PORT,
		"REMOTE_USER":                      REMOTE_USER,
		"REQBODY_ERROR":                    REQBODY_ERROR,
		"REQBODY_ERROR_MSG":                REQBODY_ERROR_MSG,
		"REQBODY_PROCESSOR":                REQBODY_PROCESSOR,
		"REQUEST_BASENAME":                 REQUEST_BASENAME,
		"REQUEST_BODY":                     REQUEST_BODY,
		"REQUEST_BODY_LENGTH":              REQUEST_BODY_LENGTH,
		"REQUEST_FILENAME":                 REQUEST_FILENAME,
		"REQUEST_LINE":                     REQUEST_LINE,
		"REQUEST_METHOD":                   REQUEST_METHOD,
		"REQUEST_PROTOCOL":                 REQUEST_PROTOCOL,
		"REQUEST_URI":                      REQUEST_URI,
		"REQUEST_URI_RAW":                  REQUEST_URI_RAW,
		"RESPONSE_BODY":                    RESPONSE_BODY,
		"RESPONSE_CONTENT_LENGTH":          RESPONSE_CONTENT_LENGTH,
		"RESPONSE_CONTENT_TYPE":            RESPONSE_CONTENT_TYPE,
		"RESPONSE_PROTOCOL":                RESPONSE_PROTOCOL,
		"RESPONSE_STATUS":                  RESPONSE_STATUS,
		"SCRIPT_BASENAME":                  SCRIPT_BASENAME,
		"SCRIPT_FILENAME":                  SCRIPT_FILENAME,
		"SCRIPT_GID":                       SCRIPT_GID,
		"SCRIPT_GROUPNAME":                 SCRIPT_GROUPNAME,
		"SCRIPT_MODE":                      SCRIPT_MODE,
		"SCRIPT_UID":                       SCRIPT_UID,
		"SCRIPT_USERNAME":                  SCRIPT_USERNAME,
		"SDBM_DELETE_ERROR":                SDBM_DELETE_ERROR,
		"SERVER_ADDR":                      SERVER_ADDR,
		"SERVER_NAME":                      SERVER_NAME,
		"SERVER_PORT":                      SERVER_PORT,
		"SESSIONID":                        SESSIONID,
		"STATUS_LINE":                      STATUS_LINE,
		"STREAM_INPUT_BODY":                STREAM_INPUT_BODY,
		"STREAM_OUTPUT_BODY":               STREAM_OUTPUT_BODY,
		"TIME":                             TIME,
		"TIME_DAY":                         TIME_DAY,
		"TIME_EPOCH":                       TIME_EPOCH,
		"TIME_HOUR":                        TIME_HOUR,
		"TIME_MIN":                         TIME_MIN,
		"TIME_MON":                         TIME_MON,
		"TIME_SEC":                         TIME_SEC,
		"TIME_WDAY":                        TIME_WDAY,
		"TIME_YEAR":                        TIME_YEAR,
		"UNIQUE_ID":                        UNIQUE_ID,
		"URLENCODED_ERROR":                 URLENCODED_ERROR,
		"USERAGENT_IP":                     USERAGENT_IP,
		"USERID":                           USERID,
		"WEBAPPID":                         WEBAPPID,
		"WEBSERVER_ERROR_LOG":              WEBSERVER_ERROR_LOG,
		"MSC_PCRE_ERROR":                   MSC_PCRE_ERROR,
		"MULTIPART_BOUNDARY_QUOTED":        MULTIPART_BOUNDARY_QUOTED,
		"MULTIPART_BOUNDARY_WHITESPACE":    MULTIPART_BOUNDARY_WHITESPACE,
		"MULTIPART_DATA_AFTER":             MULTIPART_DATA_AFTER,
		"MULTIPART_DATA_BEFORE":            MULTIPART_DATA_BEFORE,
		"MULTIPART_FILE_LIMIT_EXCEEDED":    MULTIPART_FILE_LIMIT_EXCEEDED,
		"MULTIPART_HEADER_FOLDING":         MULTIPART_HEADER_FOLDING,
		"MULTIPART_INVALID_HEADER_FOLDING": MULTIPART_INVALID_HEADER_FOLDING,
		"MULTIPART_INVALID_PART":           MULTIPART_INVALID_PART,
		"MULTIPART_INVALID_QUOTING":        MULTIPART_INVALID_QUOTING,
		"MULTIPART_LF_LINE":                MULTIPART_LF_LINE,
		"MULTIPART_MISSING_SEMICOLON":      MULTIPART_MISSING_SEMICOLON,
		"MULTIPART_SEMICOLON_MISSING":      MULTIPART_SEMICOLON_MISSING,
		"REQBODY_PROCESSOR_ERROR":          REQBODY_PROCESSOR_ERROR,
		"REQBODY_PROCESSOR_ERROR_MSG":      REQBODY_PROCESSOR_ERROR_MSG,
		"STATUS":                           STATUS,
	}
)

func VariablesToString(variables []Variable, separator string) string {
	result := ""
	for i, variable := range variables {
		if variable.Excluded {
			result += "!"
		}
		result += variable.Name.String()
		if i != len(variables)-1 {
			result += separator
		}
	}
	return result
}

func stringToVariableName(name string) VariableName {
	variable, exists := allVariables[name]
	if !exists {
		return UNKNOWN_VAR
	}
	return variable
}

func (v VariableName) MarshalYAML() (interface{}, error) {
	if v == UNKNOWN_VAR {
		return nil, fmt.Errorf("Unknown variable name")
	}
	return v.String(), nil
}

func (v *VariableName) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var name string
	if err := unmarshal(&name); err != nil {
		return err
	}
	variableConst := stringToVariableName(name)
	if variableConst == UNKNOWN_VAR {
		return fmt.Errorf("Variable name %s is not valid", name)
	}
	*v = variableConst
	return nil
}
