package types

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.yaml.in/yaml/v4"
)

var (
	varTests = []struct {
		variable VariableName
		yamlStr  string
	}{
		{ARGS_COMBINED_SIZE, "ARGS_COMBINED_SIZE"},
		{AUTH_TYPE, "AUTH_TYPE"},
		{DURATION, "DURATION"},
		{FILES_COMBINED_SIZE, "FILES_COMBINED_SIZE"},
		{FILES_NAMES, "FILES_NAMES"},
		{FILES_SIZES, "FILES_SIZES"},
		{FILES_TMP_CONTENT, "FILES_TMP_CONTENT"},
		{FILES_TMPNAMES, "FILES_TMPNAMES"},
		{FULL_REQUEST, "FULL_REQUEST"},
		{FULL_REQUEST_LENGTH, "FULL_REQUEST_LENGTH"},
		{HIGHEST_SEVERITY, "HIGHEST_SEVERITY"},
		{INBOUND_DATA_ERROR, "INBOUND_DATA_ERROR"},
		{MATCHED_VAR, "MATCHED_VAR"},
		{MATCHED_VAR_NAME, "MATCHED_VAR_NAME"},
		{MODSEC_BUILD, "MODSEC_BUILD"},
		{MSC_PCRE_LIMITS_EXCEEDED, "MSC_PCRE_LIMITS_EXCEEDED"},
		{MULTIPART_CRLF_LF_LINES, "MULTIPART_CRLF_LF_LINES"},
		{MULTIPART_FILENAME, "MULTIPART_FILENAME"},
		{MULTIPART_NAME, "MULTIPART_NAME"},
		{MULTIPART_STRICT_ERROR, "MULTIPART_STRICT_ERROR"},
		{MULTIPART_UNMATCHED_BOUNDARY, "MULTIPART_UNMATCHED_BOUNDARY"},
		{OUTBOUND_DATA_ERROR, "OUTBOUND_DATA_ERROR"},
		{PATH_INFO, "PATH_INFO"},
		{PERF_ALL, "PERF_ALL"},
		{PERF_COMBINED, "PERF_COMBINED"},
		{PERF_GC, "PERF_GC"},
		{PERF_LOGGING, "PERF_LOGGING"},
		{PERF_PHASE1, "PERF_PHASE1"},
		{PERF_PHASE2, "PERF_PHASE2"},
		{PERF_PHASE3, "PERF_PHASE3"},
		{PERF_PHASE4, "PERF_PHASE4"},
		{PERF_PHASE5, "PERF_PHASE5"},
		{PERF_SREAD, "PERF_SREAD"},
		{PERF_SWRITE, "PERF_SWRITE"},
		{QUERY_STRING, "QUERY_STRING"},
		{REMOTE_ADDR, "REMOTE_ADDR"},
		{REMOTE_HOST, "REMOTE_HOST"},
		{REMOTE_PORT, "REMOTE_PORT"},
		{REMOTE_USER, "REMOTE_USER"},
		{REQBODY_ERROR, "REQBODY_ERROR"},
		{REQBODY_ERROR_MSG, "REQBODY_ERROR_MSG"},
		{REQBODY_PROCESSOR, "REQBODY_PROCESSOR"},
		{REQUEST_BASENAME, "REQUEST_BASENAME"},
		{REQUEST_BODY, "REQUEST_BODY"},
		{REQUEST_BODY_LENGTH, "REQUEST_BODY_LENGTH"},
		{REQUEST_FILENAME, "REQUEST_FILENAME"},
		{REQUEST_LINE, "REQUEST_LINE"},
		{REQUEST_METHOD, "REQUEST_METHOD"},
		{REQUEST_PROTOCOL, "REQUEST_PROTOCOL"},
		{REQUEST_URI, "REQUEST_URI"},
		{REQUEST_URI_RAW, "REQUEST_URI_RAW"},
		{RESPONSE_BODY, "RESPONSE_BODY"},
		{RESPONSE_CONTENT_LENGTH, "RESPONSE_CONTENT_LENGTH"},
		{RESPONSE_CONTENT_TYPE, "RESPONSE_CONTENT_TYPE"},
		{RESPONSE_PROTOCOL, "RESPONSE_PROTOCOL"},
		{RESPONSE_STATUS, "RESPONSE_STATUS"},
		{RESOURCE, "RESOURCE"},
		{SCRIPT_BASENAME, "SCRIPT_BASENAME"},
		{SCRIPT_FILENAME, "SCRIPT_FILENAME"},
		{SCRIPT_GID, "SCRIPT_GID"},
		{SCRIPT_GROUPNAME, "SCRIPT_GROUPNAME"},
		{SCRIPT_MODE, "SCRIPT_MODE"},
		{SCRIPT_UID, "SCRIPT_UID"},
		{SCRIPT_USERNAME, "SCRIPT_USERNAME"},
		{SDBM_DELETE_ERROR, "SDBM_DELETE_ERROR"},
		{SERVER_ADDR, "SERVER_ADDR"},
		{SERVER_NAME, "SERVER_NAME"},
		{SERVER_PORT, "SERVER_PORT"},
		{SESSIONID, "SESSIONID"},
		{STATUS_LINE, "STATUS_LINE"},
		{STREAM_INPUT_BODY, "STREAM_INPUT_BODY"},
		{STREAM_OUTPUT_BODY, "STREAM_OUTPUT_BODY"},
		{TIME, "TIME"},
		{TIME_DAY, "TIME_DAY"},
		{TIME_EPOCH, "TIME_EPOCH"},
		{TIME_HOUR, "TIME_HOUR"},
		{TIME_MIN, "TIME_MIN"},
		{TIME_MON, "TIME_MON"},
		{TIME_SEC, "TIME_SEC"},
		{TIME_WDAY, "TIME_WDAY"},
		{TIME_YEAR, "TIME_YEAR"},
		{UNIQUE_ID, "UNIQUE_ID"},
		{URLENCODED_ERROR, "URLENCODED_ERROR"},
		{USER, "USER"},
		{USERAGENT_IP, "USERAGENT_IP"},
		{USERID, "USERID"},
		{WEBAPPID, "WEBAPPID"},
		{WEBSERVER_ERROR_LOG, "WEBSERVER_ERROR_LOG"},
		{MSC_PCRE_ERROR, "MSC_PCRE_ERROR"},
		{MULTIPART_BOUNDARY_QUOTED, "MULTIPART_BOUNDARY_QUOTED"},
		{MULTIPART_BOUNDARY_WHITESPACE, "MULTIPART_BOUNDARY_WHITESPACE"},
		{MULTIPART_DATA_AFTER, "MULTIPART_DATA_AFTER"},
		{MULTIPART_DATA_BEFORE, "MULTIPART_DATA_BEFORE"},
		{MULTIPART_FILE_LIMIT_EXCEEDED, "MULTIPART_FILE_LIMIT_EXCEEDED"},
		{MULTIPART_HEADER_FOLDING, "MULTIPART_HEADER_FOLDING"},
		{MULTIPART_INVALID_HEADER_FOLDING, "MULTIPART_INVALID_HEADER_FOLDING"},
		{MULTIPART_INVALID_PART, "MULTIPART_INVALID_PART"},
		{MULTIPART_INVALID_QUOTING, "MULTIPART_INVALID_QUOTING"},
		{MULTIPART_LF_LINE, "MULTIPART_LF_LINE"},
		{MULTIPART_MISSING_SEMICOLON, "MULTIPART_MISSING_SEMICOLON"},
		{MULTIPART_SEMICOLON_MISSING, "MULTIPART_SEMICOLON_MISSING"},
		{REQBODY_PROCESSOR_ERROR, "REQBODY_PROCESSOR_ERROR"},
		{REQBODY_PROCESSOR_ERROR_MSG, "REQBODY_PROCESSOR_ERROR_MSG"},
		{STATUS, "STATUS"},
	}
)

func TestVariableNameToString(t *testing.T) {
	for _, tt := range varTests {
		t.Run(tt.yamlStr, func(t *testing.T) {
			if tt.variable.String() != tt.yamlStr {
				t.Errorf("Expected %q, got %q", tt.yamlStr, tt.variable.String())
			}
		})
	}
}

func TestStringToVariableName(t *testing.T) {
	for _, tt := range varTests {
		t.Run(tt.yamlStr, func(t *testing.T) {
			variable := stringToVariableName(tt.yamlStr)
			if variable != tt.variable {
				t.Errorf("Expected %q, got %q", tt.variable, variable)
			}
		})
	}
}

func TestMarshalVariableName(t *testing.T) {
	for _, tt := range varTests {
		t.Run(tt.yamlStr, func(t *testing.T) {
			data, err := yaml.Marshal(tt.variable)
			if err != nil {
				t.Fatalf("Failed to marshal: %v", err)
			}
			if string(data) != tt.yamlStr+"\n" {
				t.Errorf("Expected %q, got %q", tt.yamlStr+"\n", data)
			}
		})
	}
}

func TestUnknownVariableName(t *testing.T) {
	t.Run("marshal unknown", func(t *testing.T) {
		unknown := UNKNOWN_VAR
		_, err := unknown.MarshalYAML()
		assert.Error(t, err)
		assert.Equal(t, "Unknown variable name", err.Error())
	})
}
